cache:
  directories:
  - "$HOME/.pub-cache"
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
#env:
#  - GO111MODULE=on
jobs:
  include:
  - stage: deployAPK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git
    # build aar
    - git clone https://github.com/OpenIoTHub/gateway-go.git
    # download golang
    - wget -q https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz
    - sudo tar -zxf go1.14.1.linux-amd64.tar.gz -C /usr/local
    - export GOROOT=/usr/local/go
    - export GOPATH=/home/travis/go
    - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    - go version
    - go env
    # download ndk
    - wget -q https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
    - sudo unzip -q android-ndk-r21-linux-x86_64.zip -d $ANDROID_HOME
    - export ANDROID_NDK_HOME=$ANDROID_HOME/android-ndk-r21
    # install gomobile
    - go get golang.org/x/mobile/cmd/gomobile
    - go get golang.org/x/mobile/cmd/gobind
    - gomobile init
    - gomobile version
    - pwd
    - go get -u github.com/OpenIoTHub/gateway-go
#    - find / client.aar
    - cd gateway-go/client
    - go env -w GO111MODULE=off
    - go env
    - gomobile bind -target=android .
    - cd ../..
    - rm -rf android/app/libs/*.aar
    - ls -a
    - cp ./gateway-go/client/client.aar android/app/libs
    # build aar over
    script:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "platforms;android-29"
    - mkdir release
    - ./flutter/bin/flutter doctor -v
    - ./flutter/bin/flutter pub get
    - ./flutter/bin/flutter clean
    - ./flutter/bin/flutter -v build apk --release --split-per-abi
    - cp build/app/outputs/apk/release/app-armeabi-v7a-release.apk ./phicomm-r1-install-gateway
    - zip phicomm-r1-install-gateway.zip phicomm-r1-install-gateway/*
    - mv phicomm-r1-install-gateway.zip ./release
    - mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk ./release
    - mv build/app/outputs/apk/release/app-arm64-v8a-release.apk ./release
    - mv build/app/outputs/apk/release/app-x86_64-release.apk ./release
    - ./flutter/bin/flutter -v build apk --release
    - mv build/app/outputs/apk/release/app-release.apk ./release
    - ./flutter/bin/flutter --version
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: tIC0p7eQNGas5h0OQFap54IawkHWB1pH2sybLelm+bb2pREHdDtwQH2VfspGzS2c8Q51B99PmE6UwtYESO4iqMnNlUN51XWcX50nA65tDWHdQUbd/J/7EcexjoPgqfxZ99qJAPXZfuu0Hk1gDqHjx1NmCw+gwbThuOu/P3cMztb88fYXzQODUqL1PZSSSVDS4xJN+bLWsMlf1PooS+oTEaWP5f6yXCPF7dHu9hcHqdO+9dOfLOD9pkfCZE7ml0u9tpTGeZ0kUOcJUBJQsoI23dyzmz2JBPY/zRQdkHDbWhuF7G7cyW7GjllK83/PMXWSl9veS90BRp30d6Snz8YO3cLU41+dCAX3KvpS5PHJEwWDSObuepGipYzGSV1rqBILEvEdiiR0ynO5UBQ600BbspdcCrvi0cA7enjGNoNETo8GXKHnmSESo4rKt4OBww110Mq44Pl1XxxbljxBDaPU0Qsksf0+edf+J2yJARs41/OgENuc8PLDcO41GQH4kFiDLoDYIB9HJspgsOBzMi/QsHFjp3UL/9ewU2fT0S7hGq6CrXaKYdLHGe9e4+bWXnETwTt2uKo6ov27VyymvbahEtgjuXiJTxANB6t30wwPYSASIPhXAxTr9lLYn7LHKvsstjiupTFkc7EpKC9n2NKEH5qhD5c68i3cw+sertyhHuM=
      file:
      - release/app-armeabi-v7a-release.apk
      - release/app-arm64-v8a-release.apk
      - release/app-x86_64-release.apk
      - release/app-release.apk
      - release/phicomm-r1-install-gateway.zip
      on:
        tags: true
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- openssl aes-256-cbc -K $encrypted_9bf81d20de01_key -iv $encrypted_9bf81d20de01_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar -C ./android
