cache:
  directories:
  - "$HOME/.pub-cache"
jobs:
  include:
  - stage: deployAPK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
#    env: APK_OUTPUT=build/app/outputs/apk/release/app-arm64-v8a-release.apk
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone --branch v1.9.3 https://github.com/flutter/flutter.git
#    - git clone https://github.com/OpenIoTHub/flutter_natcloud_service.git ../flutter_natcloud_service
    script:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "platforms;android-29"
#    - "./flutter/bin/flutter upgrade"
    - "./flutter/bin/flutter doctor -v"
#    - "./flutter/bin/flutter version v1.9.0"
    - "./flutter/bin/flutter pub get"
    - "./flutter/bin/flutter -v build apk --release --split-per-abi"
    - "./flutter/bin/flutter --version"
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: FJ/9t6TilxefjtU64QVjKea/qR+cLUv+dOti+3aspzudcUGWuCyUOKudhtc+PKv1B7pzjrwcAm4iNs4DD4Mm/DFdRmLgjL9+Xg8RLq6pEanr+apc8qG/nRA+NSD5F9Zkj7I4cVp4X2GhXvGJ1kMxt34SazcskdQJwnbLKcVQwXlWYelf1XbI24EZJHNyA+k1Oj980zG5WE2DJ4ETGHqzjB2NutDh1OAI64l4ZUv1/VEysJejsW1popoGbu0CN7/UY6Oedzqiv1NEbcBIez7VzN3lqFwTpfyQB/yglj6yXKuNutJjlvgjOy8a/wD4m9SGlZjrQ30ebB8Pol906T98qqyg/cT7aBc0GZZ0g19hvbheJwyq21yVy5Mf/VvQa389Ud0Kk27SmYDvyPhDyIB4vhT8pC0qDAnwaIEk+q1FkriMgtdrC+oCBuUe9bAeVymXSDc9yypaKbB8KU9xpLKOeznKe/cTIToM5TlGjWI0K1amdG/DVItwS5Xxx5sfLIjAoWghlfqdJI/znKLHkKQL4oEx8/pOcY652efFoNK0PBiYc7HMRm8UEQviZCqS9l08HEvtvSI5soyNQ2OOQa8PiD63YznwDemwP8AqUHiJnw7TRuOxhvINfG1eVLYqinPD/NkH9UVdP3eVkmjrkRng2pkYBAavRLyZuLosUFtVhXQ=
      file:
        - "build/app/outputs/apk/release/app-armeabi-v7a-release.apk"
        - "build/app/outputs/apk/release/app-arm64-v8a-release.apk"
      on:
        tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_f0033d4e34c5_key -iv $encrypted_f0033d4e34c5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar -C ./android
