cache:
  directories:
  - "$HOME/.pub-cache"
env:
  - GO111MODULE=on
jobs:
  include:
  - stage: deployAPK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git
    # build aar
    - go version
    - git clone https://github.com/OpenIoTHub/gateway-go.git
    - wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
    - sudo tar -zxf go1.14.1.linux-amd64.tar.gz -C /usr/local
    - export GOROOT=/usr/local/go
    - export GOPATH=/home/travis/go
    - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    - go version
#    - git clone https://github.com/golang/mobile $GOPATH/src/golang.org/x/mobile
#    - go install golang.org/x/mobile/cmd/gomobile
#    - go install golang.org/x/mobile/cmd/gobind
    - go get golang.org/x/mobile/cmd/gomobile
    - gomobile init
    - gomobile version
    - cd gateway-go/mobile
    - gomobile bind -target=android
    - rm -rf ../../GateWay/android/app/libs/*.aar
    - ls -a
    - cp ./client.aar ../../GateWay/android/app/libs
    - cd ../../GateWay
    # build aar over
    script:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "platforms;android-29"
    - "./flutter/bin/flutter doctor -v"
    - "./flutter/bin/flutter pub get"
    - "./flutter/bin/flutter -v build apk --release --split-per-abi"
    - "./flutter/bin/flutter --version"
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: tIC0p7eQNGas5h0OQFap54IawkHWB1pH2sybLelm+bb2pREHdDtwQH2VfspGzS2c8Q51B99PmE6UwtYESO4iqMnNlUN51XWcX50nA65tDWHdQUbd/J/7EcexjoPgqfxZ99qJAPXZfuu0Hk1gDqHjx1NmCw+gwbThuOu/P3cMztb88fYXzQODUqL1PZSSSVDS4xJN+bLWsMlf1PooS+oTEaWP5f6yXCPF7dHu9hcHqdO+9dOfLOD9pkfCZE7ml0u9tpTGeZ0kUOcJUBJQsoI23dyzmz2JBPY/zRQdkHDbWhuF7G7cyW7GjllK83/PMXWSl9veS90BRp30d6Snz8YO3cLU41+dCAX3KvpS5PHJEwWDSObuepGipYzGSV1rqBILEvEdiiR0ynO5UBQ600BbspdcCrvi0cA7enjGNoNETo8GXKHnmSESo4rKt4OBww110Mq44Pl1XxxbljxBDaPU0Qsksf0+edf+J2yJARs41/OgENuc8PLDcO41GQH4kFiDLoDYIB9HJspgsOBzMi/QsHFjp3UL/9ewU2fT0S7hGq6CrXaKYdLHGe9e4+bWXnETwTt2uKo6ov27VyymvbahEtgjuXiJTxANB6t30wwPYSASIPhXAxTr9lLYn7LHKvsstjiupTFkc7EpKC9n2NKEH5qhD5c68i3cw+sertyhHuM=
      file:
      - build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      - build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - build/app/outputs/apk/release/app-x86_64-release.apk
      on:
        tags: true
before_install:
#- export PATH=/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/.rvm/bin:/usr/local/android-sdk/tools/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/gopath/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/android-sdk/tools:/usr/local/android-sdk/platform-tools:/opt/pyenv/bin
#- which go
- echo ========
- echo $PATH
- openssl aes-256-cbc -K $encrypted_9bf81d20de01_key -iv $encrypted_9bf81d20de01_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar -C ./android
